from .cpu.functions.async_one_random import cpu_converge_async_one_random
from .cpu.functions.async_random_order import cpu_converge_async_random_order
from .cpu.functions.synchronous import cpu_converge_sync
